import { type NextPage } from "next";
import Head from "next/head";
import { type ChangeEvent, useState, useEffect, useRef } from "react";
import { ThreeDots } from "react-loader-spinner";

import { api } from "~/utils/api";
import { AIaus, AIeu, AIna, AIRegion, Chatter } from "~/utils/enums";

const Home: NextPage = () => {
  const TEXTAREA_COLS = 100;
  const TEXTAREA_ROWS = 2;
  const HISTORY_LIMIT = 50;

  const [sendAllowed, setSendAllowed] = useState<boolean>(false);
  const [message, setMessage] = useState<string>("");
  const [parentId, setParentId] = useState<string>("");
  const [convoId, setConvoId] = useState<string | undefined>("");
  const [voiceRegion, setVoiceRegion] = useState<string>("NA");
  const [voiceType, setVoiceType] = useState<string>("en-US-AmberNeural");

  const [messageHistory, setMessageHistory] = useState<[Chatter, string][]>([]);

  const didLoad = useRef<boolean>(false);

  const scrollBottomRef = useRef<HTMLDivElement | null>(null);

  const aiResponse = api.response.respond.useMutation();

  const sendData = async () => {
    setMessageHistory((m) => [...m, [Chatter.HUMAN, message]]);
    await aiResponse.mutateAsync({
      text: message,
      parentId,
      convoId,
      voiceType,
    });
    setMessage("");
    setSendAllowed(false);
  };

  const validateTextArea = (e: ChangeEvent<HTMLTextAreaElement>) => {
    setMessage(e.target.value.replace("\n", ""));
    setSendAllowed(e.target.value.trim() ? true : false);
  };

  const checkSubmit = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    e.preventDefault();
    if (e.keyCode == 13 && e.shiftKey == false && sendAllowed) {
      void sendData();
    }
  };

  const clearTextArea = () => {
    setMessage("");
    setParentId("");
    setConvoId("");
    setMessageHistory([]);
    setSendAllowed(false);
  };

  const playBuffer = (audioDataString: string) => {
    const uint8Array = new Uint8Array(
      JSON.parse(audioDataString) as Iterable<number>
    );
    const audioData: ArrayBuffer = uint8Array.buffer;
    const audioContext = new AudioContext();
    const source = audioContext.createBufferSource();
    void audioContext.decodeAudioData(audioData, (decodedData) => {
      source.buffer = decodedData;
      source.connect(audioContext.destination);
      source.start();
    });
  };

  const determineVoiceDropdown = () => {
    switch (voiceRegion) {
      case AIRegion.NORTH_AMERICA:
        return AIna;
      case AIRegion.AUSTRALIA:
        return AIaus;
      case AIRegion.EUROPE:
        return AIeu;
      default:
        return AIna;
    }
  };

  useEffect(() => {
    if (didLoad.current && aiResponse.data) {
      setMessageHistory((m) => [...m, [Chatter.AI, aiResponse.data.text]]);
      setParentId(aiResponse.data.parentId);
      setConvoId(aiResponse.data.convoId);
      playBuffer(aiResponse.data.voice);
    } else didLoad.current = true;
  }, [aiResponse.data]);

  useEffect(() => {
    messageHistory.length >= HISTORY_LIMIT && messageHistory.shift();
    scrollBottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messageHistory]);

  return (
    <>
      <Head>
        <title>Ryans AI Convos</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="fixed h-screen w-screen bg-zinc-900">
        <div className="flex h-full flex-col items-center gap-2 rounded-lg border px-4 py-4 md:m-auto md:w-1/2">
          <div className="flex flex-col text-center">
            <h2 className="text-3xl text-white md:text-4xl">
              Text Chat With AI
            </h2>
            <h2 className="text-sm text-white md:text-base">By Ryan Coppa</h2>
          </div>
          <div className="flex w-3/4 items-center justify-evenly text-xs text-white md:text-base">
            <div className="flex items-center">
              <label htmlFor="region">Region</label>
              <select
                className="m-2 rounded-md border bg-transparent p-0.5 md:p-1"
                value={voiceRegion}
                onChange={(e) => setVoiceRegion(e.target.value)}
                id="region"
              >
                {Object.keys(AIRegion).map((k, i) => (
                  <option
                    className="bg-zinc-900"
                    key={i}
                    value={
                      Object.values(AIRegion)[Object.keys(AIRegion).indexOf(k)]
                    }
                  >
                    {k}
                  </option>
                ))}
              </select>
            </div>
            <div className="flex items-center">
              <label htmlFor="voice">Voice</label>
              <select
                className="m-2 rounded-md border bg-transparent p-0.5 md:p-1"
                value={voiceType}
                onChange={(e) => setVoiceType(e.target.value)}
                id="voice"
              >
                {Object.keys(determineVoiceDropdown()).map((k, i) => (
                  <option
                    className="bg-zinc-900"
                    key={i}
                    value={
                      // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
                      Object.values(determineVoiceDropdown())[
                        Object.keys(determineVoiceDropdown()).indexOf(k)
                      ]
                    }
                  >
                    {k}
                  </option>
                ))}
              </select>
            </div>
          </div>
          <div className="my-2 w-5/6 overflow-y-auto rounded-lg text-sm text-white md:text-base">
            {messageHistory.map((m, i) => (
              <div key={i} className="flex">
                <h2 className="w-12 p-1 ">{m[0]}</h2>
                <div
                  className={`my-1 w-full whitespace-pre-wrap rounded-lg bg-opacity-25 px-6 text-left font-montserrat ${
                    m[0] === Chatter.HUMAN ? "bg-cyan-custom" : "bg-cyan-900"
                  }`}
                  key={i}
                >
                  {m[1]}
                </div>
              </div>
            ))}
            {aiResponse.isLoading && (
              <div className="flex">
                <h2 className="w-12 p-1">AI</h2>
                <div className="my-1 w-full rounded-lg bg-cyan-900 bg-opacity-25 px-12">
                  <ThreeDots
                    height="20"
                    width="20"
                    radius="9"
                    color="#4fa94d"
                    ariaLabel="three-dots-loading"
                    wrapperStyle={{}}
                    visible={true}
                  />
                </div>
              </div>
            )}
            <div ref={scrollBottomRef}></div>
          </div>
          <textarea
            className="mt-auto h-12 w-5/6 resize-none rounded-lg border bg-transparent p-2 text-sm text-white md:h-20"
            placeholder="Enter your prompt..."
            spellCheck="false"
            value={message}
            rows={TEXTAREA_ROWS}
            cols={TEXTAREA_COLS}
            maxLength={TEXTAREA_COLS * TEXTAREA_ROWS}
            onChange={validateTextArea}
            onKeyUp={checkSubmit}
          />
          <div className="my-2 flex w-full justify-evenly text-white md:text-xl">
            <button
              className="rounded-lg border px-6 py-2 hover:bg-violet-900 disabled:opacity-25 disabled:hover:bg-transparent"
              // eslint-disable-next-line @typescript-eslint/no-misused-promises
              onClick={sendData}
              type="submit"
              disabled={aiResponse.isLoading || !sendAllowed}
            >
              Send
            </button>
            <button
              className="rounded-lg border px-6 py-2 hover:bg-violet-900 disabled:opacity-25 disabled:hover:bg-transparent"
              onClick={clearTextArea}
              disabled={aiResponse.isLoading}
            >
              Clear
            </button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
